name: Update README and Date File with Stripe License Codes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run get.py to fetch license codes from Stripe
        run: python get.py

      - name: Update README.md and Date.md with fetched license codes
        run: |
          # 获取当前日期
          current_date=$(date +"%Y-%m-%d")

          # 读取获取到的 license_code 信息（get.py 的输出）
          license_codes=$(cat license_codes.txt)

          # 更新 README.md
          echo "# GreenHubLicence" > README.md
          eheo "获取 GreenHub 许可证" >> README.md
          echo "## 获取到的 GreenHub 许可证 （$current_date 更新）" >> README.md
          echo "```" >> README.md
          echo "$license_codes" >> README.md
          echo "```" >> README.md

          # 创建日期.md 文件并写入 license_code
          echo "## $current_date 的 GreenHub 许可证" > "$current_date.md"
          echo "```" >> "$current_date.md"
          echo "$license_codes" >> "$current_date.md"
          echo "```" >> "$current_date.md"

          # 提交更改到仓库
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md "$current_date.md"
          git commit -m "Updated README.md and added $current_date.md"
          git push
